/*
File:    tldinfo.go
Version: 1.7.0 (Split)
Updated: 2026-04-10

Description:
  TLD classification mapping for the sdproxy web UI stats.
  Extracted from publicsuffix.go to improve modularity and reduce file size.

  tldInfoMap maps TLDs to human-readable hints for the UI, comprehensively
  covering the IANA Root Zone Database.
*/

package main

// getTLDHint resolves the human-readable description of a TLD.
func getTLDHint(tld string) string {
	if hint, ok := tldInfoMap[tld]; ok {
		return hint
	}
	if len(tld) == 2 {
		return "Country Code"
	}
	return "Generic"
}

// tldInfoMap maps TLDs to human-readable hints for the UI.
// Mapped comprehensively to the IANA Root Zone Database.
// Sorted alphabetically by Category, and then by TLD.
var tldInfoMap = map[string]string{
	// Country Code TLDs (ccTLDs)
	"ac": "Country Code (Ascension Island)",
	"ad": "Country Code (Andorra)",
	"ae": "Country Code (United Arab Emirates)",
	"af": "Country Code (Afghanistan)",
	"ag": "Country Code (Antigua and Barbuda)",
	"ai": "Country Code (Anguilla)",
	"al": "Country Code (Albania)",
	"am": "Country Code (Armenia)",
	"an": "Country Code (Netherlands Antilles)",
	"ao": "Country Code (Angola)",
	"aq": "Country Code (Antarctica)",
	"ar": "Country Code (Argentina)",
	"as": "Country Code (American Samoa)",
	"at": "Country Code (Austria)",
	"au": "Country Code (Australia)",
	"aw": "Country Code (Aruba)",
	"ax": "Country Code (Åland Islands)",
	"az": "Country Code (Azerbaijan)",
	"ba": "Country Code (Bosnia and Herzegovina)",
	"bb": "Country Code (Barbados)",
	"bd": "Country Code (Bangladesh)",
	"be": "Country Code (Belgium)",
	"bf": "Country Code (Burkina Faso)",
	"bg": "Country Code (Bulgaria)",
	"bh": "Country Code (Bahrain)",
	"bi": "Country Code (Burundi)",
	"bj": "Country Code (Benin)",
	"bl": "Country Code (Saint Barthélemy)",
	"bm": "Country Code (Bermuda)",
	"bn": "Country Code (Brunei Darussalam)",
	"bo": "Country Code (Bolivia)",
	"bq": "Country Code (Bonaire, Sint Eustatius and Saba)",
	"br": "Country Code (Brazil)",
	"bs": "Country Code (Bahamas)",
	"bt": "Country Code (Bhutan)",
	"bv": "Country Code (Bouvet Island)",
	"bw": "Country Code (Botswana)",
	"by": "Country Code (Belarus)",
	"bz": "Country Code (Belize)",
	"ca": "Country Code (Canada)",
	"cc": "Country Code (Cocos (Keeling) Islands)",
	"cd": "Country Code (Democratic Republic of the Congo)",
	"cf": "Country Code (Central African Republic)",
	"cg": "Country Code (Congo)",
	"ch": "Country Code (Switzerland)",
	"ci": "Country Code (Côte d'Ivoire)",
	"ck": "Country Code (Cook Islands)",
	"cl": "Country Code (Chile)",
	"cm": "Country Code (Cameroon)",
	"cn": "Country Code (China)",
	"co": "Country Code (Colombia)",
	"cr": "Country Code (Costa Rica)",
	"cu": "Country Code (Cuba)",
	"cv": "Country Code (Cape Verde)",
	"cw": "Country Code (Curaçao)",
	"cx": "Country Code (Christmas Island)",
	"cy": "Country Code (Cyprus)",
	"cz": "Country Code (Czech Republic)",
	"de": "Country Code (Germany)",
	"dj": "Country Code (Djibouti)",
	"dk": "Country Code (Denmark)",
	"dm": "Country Code (Dominica)",
	"do": "Country Code (Dominican Republic)",
	"dz": "Country Code (Algeria)",
	"ec": "Country Code (Ecuador)",
	"ee": "Country Code (Estonia)",
	"eg": "Country Code (Egypt)",
	"eh": "Country Code (Western Sahara)",
	"er": "Country Code (Eritrea)",
	"es": "Country Code (Spain)",
	"et": "Country Code (Ethiopia)",
	"eu": "Country Code (European Union)",
	"fi": "Country Code (Finland)",
	"fj": "Country Code (Fiji)",
	"fk": "Country Code (Falkland Islands)",
	"fm": "Country Code (Micronesia)",
	"fo": "Country Code (Faroe Islands)",
	"fr": "Country Code (France)",
	"ga": "Country Code (Gabon)",
	"gb": "Country Code (United Kingdom)",
	"gd": "Country Code (Grenada)",
	"ge": "Country Code (Georgia)",
	"gf": "Country Code (French Guiana)",
	"gg": "Country Code (Guernsey)",
	"gh": "Country Code (Ghana)",
	"gi": "Country Code (Gibraltar)",
	"gl": "Country Code (Greenland)",
	"gm": "Country Code (Gambia)",
	"gn": "Country Code (Guinea)",
	"gp": "Country Code (Guadeloupe)",
	"gq": "Country Code (Equatorial Guinea)",
	"gr": "Country Code (Greece)",
	"gs": "Country Code (South Georgia and the South Sandwich Islands)",
	"gt": "Country Code (Guatemala)",
	"gu": "Country Code (Guam)",
	"gw": "Country Code (Guinea-Bissau)",
	"gy": "Country Code (Guyana)",
	"hk": "Country Code (Hong Kong)",
	"hm": "Country Code (Heard Island and McDonald Islands)",
	"hn": "Country Code (Honduras)",
	"hr": "Country Code (Croatia)",
	"ht": "Country Code (Haiti)",
	"hu": "Country Code (Hungary)",
	"id": "Country Code (Indonesia)",
	"ie": "Country Code (Ireland)",
	"il": "Country Code (Israel)",
	"im": "Country Code (Isle of Man)",
	"in": "Country Code (India)",
	"io": "Country Code (British Indian Ocean Territory)",
	"iq": "Country Code (Iraq)",
	"ir": "Country Code (Iran)",
	"is": "Country Code (Iceland)",
	"it": "Country Code (Italy)",
	"je": "Country Code (Jersey)",
	"jm": "Country Code (Jamaica)",
	"jo": "Country Code (Jordan)",
	"jp": "Country Code (Japan)",
	"ke": "Country Code (Kenya)",
	"kg": "Country Code (Kyrgyzstan)",
	"kh": "Country Code (Cambodia)",
	"ki": "Country Code (Kiribati)",
	"km": "Country Code (Comoros)",
	"kn": "Country Code (Saint Kitts and Nevis)",
	"kp": "Country Code (North Korea)",
	"kr": "Country Code (South Korea)",
	"kw": "Country Code (Kuwait)",
	"ky": "Country Code (Cayman Islands)",
	"kz": "Country Code (Kazakhstan)",
	"la": "Country Code (Laos)",
	"lb": "Country Code (Lebanon)",
	"lc": "Country Code (Saint Lucia)",
	"li": "Country Code (Liechtenstein)",
	"lk": "Country Code (Sri Lanka)",
	"lr": "Country Code (Liberia)",
	"ls": "Country Code (Lesotho)",
	"lt": "Country Code (Lithuania)",
	"lu": "Country Code (Luxembourg)",
	"lv": "Country Code (Latvia)",
	"ly": "Country Code (Libya)",
	"ma": "Country Code (Morocco)",
	"mc": "Country Code (Monaco)",
	"md": "Country Code (Moldova)",
	"me": "Country Code (Montenegro)",
	"mf": "Country Code (Saint Martin)",
	"mg": "Country Code (Madagascar)",
	"mh": "Country Code (Marshall Islands)",
	"mk": "Country Code (North Macedonia)",
	"ml": "Country Code (Mali)",
	"mm": "Country Code (Myanmar)",
	"mn": "Country Code (Mongolia)",
	"mo": "Country Code (Macao)",
	"mp": "Country Code (Northern Mariana Islands)",
	"mq": "Country Code (Martinique)",
	"mr": "Country Code (Mauritania)",
	"ms": "Country Code (Montserrat)",
	"mt": "Country Code (Malta)",
	"mu": "Country Code (Mauritius)",
	"mv": "Country Code (Maldives)",
	"mw": "Country Code (Malawi)",
	"mx": "Country Code (Mexico)",
	"my": "Country Code (Malaysia)",
	"mz": "Country Code (Mozambique)",
	"na": "Country Code (Namibia)",
	"nc": "Country Code (New Caledonia)",
	"ne": "Country Code (Niger)",
	"nf": "Country Code (Norfolk Island)",
	"ng": "Country Code (Nigeria)",
	"ni": "Country Code (Nicaragua)",
	"nl": "Country Code (Netherlands)",
	"no": "Country Code (Norway)",
	"np": "Country Code (Nepal)",
	"nr": "Country Code (Nauru)",
	"nu": "Country Code (Niue)",
	"nz": "Country Code (New Zealand)",
	"om": "Country Code (Oman)",
	"pa": "Country Code (Panama)",
	"pe": "Country Code (Peru)",
	"pf": "Country Code (French Polynesia)",
	"pg": "Country Code (Papua New Guinea)",
	"ph": "Country Code (Philippines)",
	"pk": "Country Code (Pakistan)",
	"pl": "Country Code (Poland)",
	"pm": "Country Code (Saint Pierre and Miquelon)",
	"pn": "Country Code (Pitcairn)",
	"pr": "Country Code (Puerto Rico)",
	"ps": "Country Code (Palestine)",
	"pt": "Country Code (Portugal)",
	"pw": "Country Code (Palau)",
	"py": "Country Code (Paraguay)",
	"qa": "Country Code (Qatar)",
	"re": "Country Code (Réunion)",
	"ro": "Country Code (Romania)",
	"rs": "Country Code (Serbia)",
	"ru": "Country Code (Russia)",
	"rw": "Country Code (Rwanda)",
	"sa": "Country Code (Saudi Arabia)",
	"sb": "Country Code (Solomon Islands)",
	"sc": "Country Code (Seychelles)",
	"sd": "Country Code (Sudan)",
	"se": "Country Code (Sweden)",
	"sg": "Country Code (Singapore)",
	"sh": "Country Code (Saint Helena)",
	"si": "Country Code (Slovenia)",
	"sj": "Country Code (Svalbard and Jan Mayen)",
	"sk": "Country Code (Slovakia)",
	"sl": "Country Code (Sierra Leone)",
	"sm": "Country Code (San Marino)",
	"sn": "Country Code (Senegal)",
	"so": "Country Code (Somalia)",
	"sr": "Country Code (Suriname)",
	"ss": "Country Code (South Sudan)",
	"st": "Country Code (São Tomé and Príncipe)",
	"su": "Country Code (Soviet Union)",
	"sv": "Country Code (El Salvador)",
	"sx": "Country Code (Sint Maarten)",
	"sy": "Country Code (Syria)",
	"sz": "Country Code (Eswatini)",
	"tc": "Country Code (Turks and Caicos Islands)",
	"td": "Country Code (Chad)",
	"tf": "Country Code (French Southern Territories)",
	"tg": "Country Code (Togo)",
	"th": "Country Code (Thailand)",
	"tj": "Country Code (Tajikistan)",
	"tk": "Country Code (Tokelau)",
	"tl": "Country Code (Timor-Leste)",
	"tm": "Country Code (Turkmenistan)",
	"tn": "Country Code (Tunisia)",
	"to": "Country Code (Tonga)",
	"tr": "Country Code (Turkey)",
	"tt": "Country Code (Trinidad and Tobago)",
	"tv": "Country Code (Tuvalu)",
	"tw": "Country Code (Taiwan)",
	"tz": "Country Code (Tanzania)",
	"ua": "Country Code (Ukraine)",
	"ug": "Country Code (Uganda)",
	"uk": "Country Code (United Kingdom)",
	"us": "Country Code (United States)",
	"uy": "Country Code (Uruguay)",
	"uz": "Country Code (Uzbekistan)",
	"va": "Country Code (Vatican City)",
	"vc": "Country Code (Saint Vincent and the Grenadines)",
	"ve": "Country Code (Venezuela)",
	"vg": "Country Code (British Virgin Islands)",
	"vi": "Country Code (U.S. Virgin Islands)",
	"vn": "Country Code (Vietnam)",
	"vu": "Country Code (Vanuatu)",
	"wf": "Country Code (Wallis and Futuna)",
	"ws": "Country Code (Samoa)",
	"ye": "Country Code (Yemen)",
	"yt": "Country Code (Mayotte)",
	"za": "Country Code (South Africa)",
	"zm": "Country Code (Zambia)",
	"zw": "Country Code (Zimbabwe)",

	// Generic TLDs (gTLDs)
	"academy": "Generic",
	"accountant": "Generic",
	"agency": "Generic",
	"app": "Generic",
	"art": "Generic",
	"band": "Generic",
	"bar": "Generic",
	"bio": "Generic",
	"biz": "Generic",
	"blog": "Generic",
	"blue": "Generic",
	"boutique": "Generic",
	"buzz": "Generic",
	"cafe": "Generic",
	"cam": "Generic",
	"camp": "Generic",
	"capital": "Generic",
	"cards": "Generic",
	"care": "Generic",
	"cash": "Generic",
	"casino": "Generic",
	"center": "Generic",
	"ceo": "Generic",
	"chat": "Generic",
	"cheap": "Generic",
	"city": "Generic",
	"claims": "Generic",
	"clinic": "Generic",
	"clothing": "Generic",
	"cloud": "Generic",
	"club": "Generic",
	"coach": "Generic",
	"codes": "Generic",
	"coffee": "Generic",
	"com": "Generic",
	"community": "Generic",
	"company": "Generic",
	"computer": "Generic",
	"condos": "Generic",
	"construction": "Generic",
	"consulting": "Generic",
	"contractors": "Generic",
	"cool": "Generic",
	"credit": "Generic",
	"creditcard": "Generic",
	"cruises": "Generic",
	"dance": "Generic",
	"dating": "Generic",
	"deals": "Generic",
	"degree": "Generic",
	"delivery": "Generic",
	"democrat": "Generic",
	"dental": "Generic",
	"dentist": "Generic",
	"design": "Generic",
	"dev": "Generic",
	"diamonds": "Generic",
	"digital": "Generic",
	"direct": "Generic",
	"directory": "Generic",
	"discount": "Generic",
	"dog": "Generic",
	"domains": "Generic",
	"education": "Generic",
	"email": "Generic",
	"energy": "Generic",
	"engineer": "Generic",
	"engineering": "Generic",
	"enterprises": "Generic",
	"equipment": "Generic",
	"estate": "Generic",
	"events": "Generic",
	"exchange": "Generic",
	"expert": "Generic",
	"exposed": "Generic",
	"express": "Generic",
	"fail": "Generic",
	"family": "Generic",
	"fan": "Generic",
	"farm": "Generic",
	"finance": "Generic",
	"financial": "Generic",
	"fish": "Generic",
	"fitness": "Generic",
	"flights": "Generic",
	"florist": "Generic",
	"foo": "Generic",
	"foundation": "Generic",
	"fund": "Generic",
	"furniture": "Generic",
	"fyi": "Generic",
	"gallery": "Generic",
	"games": "Generic",
	"gift": "Generic",
	"gifts": "Generic",
	"glass": "Generic",
	"global": "Generic",
	"gold": "Generic",
	"golf": "Generic",
	"graphics": "Generic",
	"gratis": "Generic",
	"gripe": "Generic",
	"group": "Generic",
	"guide": "Generic",
	"guru": "Generic",
	"healthcare": "Generic",
	"hockey": "Generic",
	"holdings": "Generic",
	"holiday": "Generic",
	"host": "Generic",
	"hosting": "Generic",
	"house": "Generic",
	"how": "Generic",
	"immo": "Generic",
	"industries": "Generic",
	"info": "Generic",
	"ink": "Generic",
	"institute": "Generic",
	"insure": "Generic",
	"international": "Generic",
	"investments": "Generic",
	"jewelry": "Generic",
	"kim": "Generic",
	"kitchen": "Generic",
	"land": "Generic",
	"lawyer": "Generic",
	"lease": "Generic",
	"legal": "Generic",
	"life": "Generic",
	"lighting": "Generic",
	"limited": "Generic",
	"limo": "Generic",
	"link": "Generic",
	"live": "Generic",
	"loans": "Generic",
	"lol": "Generic",
	"ltd": "Generic",
	"maison": "Generic",
	"management": "Generic",
	"market": "Generic",
	"marketing": "Generic",
	"mba": "Generic",
	"media": "Generic",
	"memorial": "Generic",
	"menu": "Generic",
	"money": "Generic",
	"mortgage": "Generic",
	"name": "Generic",
	"net": "Generic",
	"network": "Generic",
	"news": "Generic",
	"ninja": "Generic",
	"online": "Generic",
	"org": "Generic",
	"page": "Generic",
	"partners": "Generic",
	"parts": "Generic",
	"photography": "Generic",
	"photos": "Generic",
	"pictures": "Generic",
	"pizza": "Generic",
	"place": "Generic",
	"plumbing": "Generic",
	"plus": "Generic",
	"press": "Generic",
	"pro": "Generic",
	"productions": "Generic",
	"promo": "Generic",
	"properties": "Generic",
	"pub": "Generic",
	"recipes": "Generic",
	"red": "Generic",
	"rehab": "Generic",
	"rentals": "Generic",
	"repair": "Generic",
	"report": "Generic",
	"republican": "Generic",
	"restaurant": "Generic",
	"reviews": "Generic",
	"rip": "Generic",
	"rocks": "Generic",
	"run": "Generic",
	"sale": "Generic",
	"salon": "Generic",
	"sarl": "Generic",
	"school": "Generic",
	"schule": "Generic",
	"services": "Generic",
	"shoes": "Generic",
	"shop": "Generic",
	"shopping": "Generic",
	"show": "Generic",
	"singles": "Generic",
	"site": "Generic",
	"soccer": "Generic",
	"software": "Generic",
	"solar": "Generic",
	"solutions": "Generic",
	"soy": "Generic",
	"space": "Generic",
	"store": "Generic",
	"studio": "Generic",
	"style": "Generic",
	"supplies": "Generic",
	"supply": "Generic",
	"support": "Generic",
	"surgery": "Generic",
	"systems": "Generic",
	"tax": "Generic",
	"taxi": "Generic",
	"team": "Generic",
	"tech": "Generic",
	"technology": "Generic",
	"tennis": "Generic",
	"theater": "Generic",
	"tienda": "Generic",
	"tips": "Generic",
	"tires": "Generic",
	"today": "Generic",
	"tools": "Generic",
	"top": "Generic",
	"tours": "Generic",
	"town": "Generic",
	"toys": "Generic",
	"trade": "Generic",
	"training": "Generic",
	"university": "Generic",
	"vacations": "Generic",
	"ventures": "Generic",
	"vet": "Generic",
	"viajes": "Generic",
	"video": "Generic",
	"villas": "Generic",
	"vin": "Generic",
	"vip": "Generic",
	"vision": "Generic",
	"voyage": "Generic",
	"wang": "Generic",
	"watch": "Generic",
	"website": "Generic",
	"win": "Generic",
	"wine": "Generic",
	"work": "Generic",
	"works": "Generic",
	"world": "Generic",
	"wtf": "Generic",
	"xyz": "Generic",
	"zone": "Generic",

	// Infrastructure & Local
	"arpa":      "Infrastructure",
	"example":   "Infrastructure (Example)",
	"home.arpa": "Local/Private",
	"invalid":   "Infrastructure (Invalid)",
	"lan":       "Local/Private",
	"local":     "Local/Private",
	"localhost": "Local/Private",
	"onion":     "Infrastructure (Tor)",

	// Sponsored TLDs (sTLDs)
	"aero":   "Sponsored (Aviation)",
	"asia":   "Sponsored (Asia-Pacific)",
	"cat":    "Sponsored (Catalan)",
	"coop":   "Sponsored (Cooperatives)",
	"edu":    "Sponsored (Education)",
	"gov":    "Sponsored (U.S. Government)",
	"int":    "Sponsored (International Organizations)",
	"jobs":   "Sponsored (Human Resources)",
	"mil":    "Sponsored (U.S. Military)",
	"mobi":   "Sponsored (Mobile)",
	"museum": "Sponsored (Museums)",
	"post":   "Sponsored (Postal Services)",
	"tel":    "Sponsored (Telecommunications)",
	"travel": "Sponsored (Travel and Tourism)",
	"xxx":    "Sponsored (Adult Entertainment)",

	// Test TLDs (tTLDs)
	"test": "Test (Development)",
}

